# Generated by Django 4.2.1 on 2023-05-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_mail', models.CharField(max_length=50)),
                ('cust_date', models.DateField()),
                ('cust_time', models.TimeField()),
                ('cust_pers', models.IntegerField()),
            ],
        ),
    ]
