# Generated by Django 4.2.1 on 2023-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_name', models.CharField(max_length=255)),
                ('categ_type', models.CharField(choices=[('hot', 'HOT'), ('cold', 'COLD')], default='hot', max_length=10)),
            ],
        ),
    ]
